### ISSUE TITLE
[Docs]: Broken link in README.md

### ISSUE THREAD

**Issue by HGS-davidstreutker** [interactive-data-language/vscode-idl#10]
### Documentation Issue

- [ ] IDL or ENVI Hover-help Docs Bug or Missing Routine
- [ ] Typo
- [X] Documentation Bug or Broken Link
- [ ] Feedback on Existing Topic
- [ ] Request for New Topic

### Description

The link to CONTRIBUTING.md contained in the top-level README.md doesn't seem to be rendered correctly by GitHub on the project home page.  Link goes to [https://github.com/interactive-data-language/CONTRIBUTING.md](https://github.com/interactive-data-language/CONTRIBUTING.md) instead of [https://github.com/interactive-data-language/vscode-idl/blob/main/CONTRIBUTING.md](https://github.com/interactive-data-language/vscode-idl/blob/main/CONTRIBUTING.md)  

Other links render correctly.  Issue perhaps due to this one being contained in a blockquote?

**Comment by znorman-harris** [comment]
Sorry for the delay getting back to this, have had a couple of busy weeks of meetings!

Where exactly do you see this? Looking at GitHub and on the posting in the VSCode marketplace I don't see anything weird going on?

Maybe a screenshot of which link is broken?

**Comment by HGS-davidstreutker** [comment]
Yeah, I can't seem to reproduce it now either.  Maybe the site was just being flaky that day...

**Comment by znorman-harris** [comment]
Well thanks for checking again! Happy to fix it if it comes up again.
