### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by KattoQuin** [interactive-data-language/vscode-idl#13]
### Current Behavior

![image](https://github.com/interactive-data-language/vscode-idl/assets/82196186/b557dab2-3d80-4b39-b59c-c75ff0f0fd4c)
When I start a session of IDL, that error appear and I don't know how to fix.

### Expected Behavior

It should start a window for IDL on VSCode

### Steps to Reproduce

1. Install IDL extension to VSCode
2. In the extension, choose Start a session of IDL
3. The error appears

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

3.0

**Comment by znorman-harris** [comment]
What's the version of IDL that you are using and can you launch IDL through the start menu?

You should have some output when IDL fails to launch (typically licensing errors). If there isn't anything, which is what it looks like for you, then I would try to launch IDL without VSCode and verify it starts up by itself.

Additionally, what is shown in the logs? From the IDL sidebar in VSCode, you should see a button called "View Extension Logs" that will have some additional information about your setup that can help  figure out what is going on.

**Comment by znorman-harris** [comment]
Without any additional information, I'm going to close this since it has been a week. If you encounter the issue again, please include logs and verify that IDL starts on your machine without VSCode.
