### ISSUE TITLE
[Bug]: Comments at the end of code

### ISSUE THREAD

**Issue by HGS-davidstreutker** [interactive-data-language/vscode-idl#14]
### Current Behavior

Extension seems to flag any comments that appear after the code in a file.  See the screencap below:

![image](https://github.com/interactive-data-language/vscode-idl/assets/60927559/68d9d159-50dc-400f-8eb9-a7e338abd5fe)

I don't care so much about the end comment, but I do like to put dividers after all my procedures & functions...

### Expected Behavior

Extension allows comments at the end of file.

### Steps to Reproduce

1. See screencap above.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

IDL 9.0 RC

**Comment by znorman-harris** [comment]
Ah, good catch here! I think this actually came from a change to how we parse code for IDL Notebooks and main level programs. That lines up with the problem that gets reported:

![image](https://github.com/interactive-data-language/vscode-idl/assets/31664668/b475ede8-6e6a-4186-9ffa-3f2aea4c4992)

Let me see if I can get a fix in for our next release and get some regression tests. We are planning to have one next week.

**Comment by znorman-harris** [comment]
OK, this was a really easy fix :) [Fixed, added tests, and in develop](https://github.com/interactive-data-language/vscode-idl/commit/d8c596c21e7a533b2b089acbbc02d6355a3c9c47)

![image](https://github.com/interactive-data-language/vscode-idl/assets/31664668/3d451a63-5aa3-4120-85e9-34ea314ebab3)
