### ISSUE TITLE
[Bug]: !QUIET system variable set to 1

### ISSUE THREAD

**Issue by HGS-davidstreutker** [interactive-data-language/vscode-idl#16]
### Current Behavior

Looks like `!QUIET` defaults to a value of 1?  I only label this a bug as `!QUIET=0` is the default stated in the IDL help, and informational messages were getting expectedly suppressed for me...  (I realize the value can be changed locally or in the extension settings.)

### Expected Behavior

`!QUIET` defaults to 0

### Steps to Reproduce

1.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [ ] Windows

### IDL Version

IDL 9.0 RC

**Comment by znorman-harris** [comment]
Is there something in particular that you are wanting to see? 

We have always managed the `!quiet` system variable in notebooks. For example, here is the same logic in the IDL Kernel for Jupyter:

![image](https://github.com/interactive-data-language/vscode-idl/assets/31664668/9570158c-94fe-4904-a2fa-8bd3d75c2ec3)

And here is what we do in our VSCode Notebook controller:

![image](https://github.com/interactive-data-language/vscode-idl/assets/31664668/9896ee4c-b6e0-4800-97bc-837406636bfc)


`!quiet` is only set right after we start up and after you reset IDL. Meaning that you can change it within your first cell to change the behavior.

**Comment by HGS-davidstreutker** [comment]
I don't feel real strongly about it -- as you say it can be easily changed.  But I would suggest it violates the principle of least astonishment in that it is the opposite of default IDL behavior.  I use MESSAGE, /INFO for status updates throughout my code...

**Comment by HGS-davidstreutker** [comment]
It looks like I could do that already using Idl.IDL:Environment?  Thinking about it a bit, I'd be happy if it was just documented in the in the IDL example notebook, maybe where you discuss `compile_opt idl2`.

BTW, if you didn't catch it, I meant to say "**un**expectedly suppressed" in my original post...

**Comment by znorman-harris** [comment]
OK, added in a new preference for this. I'll be getting out a new release in the next day or two with this change so your code keeps working!

![image](https://github.com/interactive-data-language/vscode-idl/assets/31664668/0a465788-ce89-43c4-a301-4e59acec4fa2)

I'll close this for now since it's been added and has tests.
