### ISSUE TITLE
[Bug]: illegal-struct-op error, 85 issued for valid code

### ISSUE THREAD

**Issue by HGS-jimpendleton** [interactive-data-language/vscode-idl#20]
### Current Behavior

The following statement is flagged by the VS Code plug-in for IDL as an "illegal-struct-op", but it compiles without error:
regName = ~keyword_set(noName)
  lookup = $
    [ (regName ? { prop:'NAME', cat:'Property:Name', str:'Name' } : []), $
      { prop:'COLOR', cat:'Property:Color', str:'Color' }, $
      { prop:'ALPHA_CHANNEL', cat:'Property:Opacity', str:'Opacity' }, $
      { prop:'TEXT_SIZE', cat:'Property:TextSize', str:'Text size' }, $
      { prop:'THICK', cat:'Property:Thickness', str:'Thickness'}, $
      { prop:'RECOMPUTE', cat:'Property:OnGlass', str:'On glass' }, $
      { prop:'FONT_NAME', cat:'Property:FontName', str:'Font' }, $
      { prop:'H_ALIGN', cat:'Property:HorizontalAlignment', $
        str:'Horizontal alignment'}, $
      { prop:'V_ALIGN', cat:'Property:VerticalAlignment', $
        str:'Vertical alignment'}, $
      { prop:'LOCK', cat:'Property:Locked', str:'Locked'}]

### Expected Behavior

No syntax problem should be issued for this line of code.

### Steps to Reproduce

Copy and paste the example code into an VS Code editor.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

9.0

**Comment by znorman-harris** [comment]
Fixed in latest develop, a new release should be out in the next week or so, depending on ENVI DL release!
