### ISSUE TITLE
[Bug]: Failed to send/receive message with the IDL Language Server

### ISSUE THREAD

**Issue by bernatp3rs** [interactive-data-language/vscode-idl#4]
### Current Behavior

We used all the tips described in the previous closed issue. VSCode is properly loading node:
![Screenshot 2023-07-18 at 8 50 07 AM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/a9a76b26-e8d0-49d6-8563-86c71135e362)

And the setting "Language Server: Full Parse" is disabled:
![Screenshot 2023-07-18 at 8 50 47 AM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/9620522f-df7b-4120-aa0c-92f432675f84)

However, the following errors keeps randomly appearing: 
![Screenshot 2023-07-18 at 8 48 21 AM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/8d969b6c-6b59-4845-81c7-6e9d170199a0)

This is the log:
![Screenshot 2023-07-18 at 8 58 32 AM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/55751f6d-4f8e-4bfd-bfe8-67a8a3befed4)

After this error, basic functionality such as go-to definition and hover help stops working which reduces a lot our productivity. The previous extension was much more stable (we never had problems before), is there a way to force VSCode to use it?

### Expected Behavior

The extension shouldn't cause problems that affect our productivity

### Steps to Reproduce

1. Don't know, the problem appears randomly

### Operating System

- [X] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [ ] Windows

### IDL Version

8.5.1

**Comment by znorman-harris** [comment]
Thanks for reporting this is still an issue. It looks like our garbage collection isn't running as it is expected all the time, so I'll dig into this and see if I can get it fixed in the next day or so.

**Comment by znorman-harris** [comment]
I think you can do that through the VSCode marketplace, but I'm not 100% sure. I can tell you that the code is so old for the original extension that it doesn't build anymore, so there's no way to make a one-off installer.

About the best recommendation I can make is, if you have that much code, use node.js and also disable the "full-parse" option. For me, and on Windows, it parses 4 copies of the IDL lib folder (6200 files) in about 7.5 seconds without full parse. Unfortunately, without the full parse, you don't get the user experience we are really hoping for with problem detection and additional insights into your code before you compile anything.

One of the items on our list is to look out for performance issues (like the ones you are encountering) and that's part of the reason we haven't fully "released" the extension and done webinars and email blasts yet to sort out some of these kinks.. 

I'll keep thinking about this as there are probably some other ways we can very quickly parse files to get the basics (routines, maybe structures) so hover help, auto-complete, and go-to-definition work. Or this might include caching (one slow startup, fast after that).

**Comment by znorman-harris** [comment]
I did manage to improve the performance even more for the not-full parsing. If you are interested in trying it out, you can view it here: https://github.com/interactive-data-language/vscode-idl/releases/tag/3.1.0-preview2

Here's the before/after performance metrics for my machine with almost 8000 files. This might save you about 40% time and get you down to about 30 seconds or so if it takes a minute. To get exact timing, this output gets printed to the IDL Logs once we parse all your code on startup.

```typescript
const before = {
  lines: 2252881,
  app_platform: 'win32',
  app_arch: 'x64',
  app_cpus: 20,
  app_ram: 32,
  app_ram_used: 2.5,
  num_workers: 6,
  parse_time: 13.49,
  parse_rate: 167015,
  num_pro: 7816,
  num_save: 830,
  num_idl_task: 15,
  num_envi_task: 0,
  num_idl_json: 0,
};

const after = {
  lines: 2252881,
  app_platform: 'win32',
  app_arch: 'x64',
  app_cpus: 20,
  app_ram: 32,
  app_ram_used: 1.75,
  num_workers: 6,
  parse_time: 7.86,
  parse_rate: 286567,
  num_pro: 7816,
  num_save: 830,
  num_idl_task: 15,
  num_envi_task: 0,
  num_idl_json: 0,
};
```

**Comment by bernatp3rs** [comment]
On my Mac, the RAM usage peaks above 15Gb before it gets stabilized to ~500Mb. The system needs to use the SWAP memory to be able to handle what "node" is doing. Here is an example when it was above 8Gb:

![Screenshot 2023-07-18 at 7 35 57 PM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/62e52b42-8d83-4d06-8cc9-0a2dd54371c3)

On another note, even if the "full-parse" option is disabled, the extension finds problems to all the routines in my library. I'm wondering if this is causing performance issues as well (more than 2000 issues are reported (mostly documentation, missing the compile_opt statement and also "Duplicate procedure definition" when this is not the case)

![Screenshot 2023-07-18 at 7 43 15 PM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/c387aa54-4aed-4dc4-b459-07c02366deda)

**Comment by znorman-harris** [comment]
Hmmm. It looks like there might be something odd going on. One thing that might be good is to make sure all versions of the IDL extension are uninstalled. I have noticed that, even when you uninstall an extension and reload, the old folder sometimes hangs around.

Try this:

1. Manually uninstall the IDL extension (all of them if you have more than one)
2. Reload your VSCode window
3. From VSCode, open the extension folder (Command + Shift  + p for commands then select "Extensions: Open Extensions Folder"
4. Make sure you don't see a folder starting with "idl." and, if you do, restart VSCode another time and repeat (or manually delete the folder)
5. Install the preview of the extension from [here](https://github.com/interactive-data-language/vscode-idl/releases/tag/3.1.0-preview2)

Just to show that I can get this working on my mac, I manually installed the extension above, copied IDL's lib folder 4x, and opened on my Mac. I'm using node.js and you can see the major output from my logs below to show that we should at least have similar environments up and running.

Lastly, thanks for taking the time to try this out. If you would like to hop on a call so we can sort this out, feel free to send me an email at zachary.norman@nv5.com. I think I recognize your name from my tech support days, so I'm more than happy to spend some time to help get this working if you would like.

```
idl-client info Starting the language server using: node
idl-client info Starting language server
idl-lsp info Garbage collection enabled: true
idl-lsp info Server initialized, indexing code in these folders:
  { '/Users/user/Desktop/test': true }
idl-lsp info Attempting to index 7730 PRO file(s)
idl-lsp info Finished indexing 7730 files in 10526 ms, see below for additional information
  {
    lines: 2241955,
    app_platform: 'darwin',
    app_arch: 'x64',
    app_cpus: 16,
    app_ram: 16,
    app_ram_used: 1.75,
    num_workers: 6,
    parse_time: 10,
    parse_rate: 224165,
    num_pro: 7730,
    num_save: 735,
    num_idl_task: 15,
    num_envi_task: 0,
    num_idl_json: 0
  }
```

**Comment by bernatp3rs** [comment]
HI Zach, 

I did what you suggested and I keep having the same issues. I don't have folders starting with "idl." in my extensions. Today I reinstalled everything and look at this:
![Screenshot 2023-07-24 at 2 53 04 PM](https://github.com/interactive-data-language/vscode-idl/assets/8899703/cbaa7673-e1e8-4a26-b366-12c0e497cca3)

Totally crazy! My computer need to use the SWAP memory in order to manage he VSC IDL extension. I hope that you'll find a way to fix this.
Thanks,

Bernat

**Comment by bernatp3rs** [comment]
Sorry, I was mistaken. the same memory errors keep happening. And well, the "go-to definition"  and "hover help" are extremely slow.

**Comment by znorman-harris** [comment]
@bernatp3rs I just sent you an email with some more detail and a few questions so we can try to get this resolved. If you are using links, it might come down to your path and circular links or files being indexed multiple times because of links.

**Comment by znorman-harris** [comment]
The latest release (3.1.1) resolves the memory and a majority of the performance issues, so I'm going to close this after receiving confirmation that the extensions starts quickly now.

**Comment by bernatp3rs** [comment]
For some reason, the error appeared again today. Not at startup but when
writing new routines... Everything was stable and when I started saving new
files, node started consuming memory

[image: Screenshot 2023-07-27 at 12.39.41 PM.png]
