### ISSUE TITLE
[Bug]: Answering "Don't ask again" on "Set extension as default formatter for IDL code?" leads to being asked again

### ISSUE THREAD

**Issue by jtrl3** [interactive-data-language/vscode-idl#44]
### Current Behavior

On opening a workspace, a popup appears, asking if I would like to set the IDL for VSCode extension as the default formatter for IDL code. Pressing "No" or "Don't ask again" seems to have no effect, as the popup appears again if I restart VSCode within the same workspace.

### Expected Behavior

Clicking "Don't ask again" I expect to not be asked again about using this extension as the default formatter after a simple re-opening of VSCode within the same workspace I was working in. It seems as though my request to not be asked again was not saved.

### Steps to Reproduce

1. Open a workspace containing IDL code with the IDL for VSCode extension installed
2. Wait for popup on the bottom right that says "Set extension as default formatter for IDL code?"
3. Click "Do not ask again".
4. Restart VSCode and the popup shall reappear.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment]
Thanks for reporting this! I was able to reproduce this locally, let me take a look and see if anything has changed. I'll try to get a fix out in the next couple of days.

**Comment by znorman-harris** [comment]
OK, this was a quick fix and a missing piece of logic which has been added in. I'll get a release out here shortly with this fix and a few others.
