### ISSUE TITLE
[Feature]: Link to extension docs in Readme file

### ISSUE THREAD

**Issue by steinhh** [interactive-data-language/vscode-idl#47]
### Description

It would be nice to have a link to the (official?) documentation page (https://interactive-data-language.github.io/vscode-idl/) in the Readme file, and also in the extension description shown in VSCode itself (which might be one and the same thing). The latter is where I'm used to find such links.

### Why it Matters

Ease of access and visibility.

Right now the only link I found was after being told by a coworker that I could click on the IDL icon in the leftmost margin in VSCode, then locating the item "Open Extension docs". Having a link called "Documentation" on the Readme page/in the extension description would've saved me quite some time :).

### Suggested Behavior

N/A

### Alternate Behavior

N/A

**Comment by znorman-harris** [comment]
Thanks for reporting! This also comes at a good time for our next release where we have re-worked the readme,

You can find a preview of this on the landing page [here](https://github.com/interactive-data-language/vscode-idl/tree/develop) on our develop branch.

Hopefully that will work to solve the problem!

**Comment by steinhh** [comment]
Thanks for the quick response! But actually, could you make it a bullet at the end of the About section? Where it is now... well, my eyes automatically skip the blah-blah (sorry!) at the top to go straight for the meat...

**Comment by znorman-harris** [comment]
Ah, fair point. And easy enough to tweak. I just pushed a change to develop to add it to the end of our about section.

Let me know if this works!

**Comment by steinhh** [comment]
Perfect, thanks!
