### ISSUE TITLE
[Bug]: Some problems will be reported even though 'idl-disable' has been set

### ISSUE THREAD

**Issue by martinwiesmann** [interactive-data-language/vscode-idl#48]
### Current Behavior

When I add the line
```; idl-disable```
to the top of a file, then I would expect that the file will be parsed but non of the problems will be reported. But apparently, some of the problems are reported anyway. I see this for the problems "duplicate-func" and "duplicate-pro". There might be others.

### Expected Behavior

I would expect that all problems would be suppressed.

### Steps to Reproduce

1. Create one or more files that contain procedures and/or functions with the same name
2. Add the directory in which these file(s) are to idl.IDL.path
3. Check resulting problems

### Operating System

- [X] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [ ] Windows

### IDL Version

9.1.0

**Comment by znorman-harris** [comment]
Thanks for reporting this too! Let me take a look and verify the duplicates are being handled right. This might have been a missed test case when we added this functionality in.

**Comment by martinwiesmann** [comment]
Also those warnings will be reported: "duplicate-pro-method" and "duplicate-func-method" and "duplicate-struct".

**Comment by znorman-harris** [comment]
Thanks! And sorry this took a couple of weeks for me to get to. I had some PTO and then caught a cold coming back.

I just updated the language server to now properly handle this and added some regression tests to make sure that we handle our two cases for disabling these problems being reported (overall for a file, or individually).

I'm meeting with the team tomorrow and we will talk about getting a new release out the door in the next couple of days.

**Comment by martinwiesmann** [comment]
I hope you feel better now.

That sounds great, thanks. Looking forward to the new release.

**Comment by znorman-harris** [comment]
Thanks, I am getting there!

I'll post a message here when the release comes out to let you know.

**Comment by martinwiesmann** [comment]
The latest release did not resolve this issue. I still find many warnings even though idl-disable has been set.

E.g.:

![Screenshot 2024-11-26 at 11 31 13](https://github.com/user-attachments/assets/43d1341d-30aa-41ed-b41c-1c560b4cb18d)

**Comment by znorman-harris** [comment]
Actually, I'm wondering if this is related to symbolic links again. Let me poke around and see if I can get this replicated. I'm realizing there might be 1-2 other places missed for the symbolic link fix on parsing your path.

When you have "real" files on disk and duplicate files/routines, it does work. Here's something analogous to our test cases to demonstrate it:

![image](https://github.com/user-attachments/assets/1ecf1ea9-6c11-4b63-b096-412de2eb787f)

**Comment by znorman-harris** [comment]
OK, our symbolic link support may need to evolve a bit over time. I was able to get an environment set up on my Mac and reproduce this to some extent.

At a high level, all problems will be reported for the source file and not a linked one (so you don't have "duplicate" reports being logged for the same "file"). Again, this is likely going to be the start, we can re-evaluate if this needs to change in the future.

With my test environment, I was also surprised to discover that VSCode itself does not support editing of linked files as I would expect. With the source file and linked file displayed side-by-side, any edits made to the original (even saving on disk) do not appear in the linked file. I had to restart VSCode (or re-open the workspace) to see the changes in my code.

With that in mind, here's a screenshot of a linked file and source file not reporting duplicate problems as you were encountering originally. You can also see, on line 10, that there's a problem you only see on the left and not the right.

![image](https://github.com/user-attachments/assets/e978b1a7-3631-4ae3-a2a9-e78c338a7efa)
