### ISSUE TITLE
[Bug]: Setting routines: none formats like routines: match

### ISSUE THREAD

**Issue by steinhh** [interactive-data-language/vscode-idl#51]
### Current Behavior

Setting formatting option routines: none results in same behaviour as routines: match. 

Corollary feature request: add routines: lower as a formatting option.

### Expected Behavior

When formatting option routines is set to "none", no change is expected to the case of a routine call.

### Steps to Reproduce

1. Set formatting option routines: none
2. Create file "uppercase_test.pro" (see "additional information")
3. Format file
4. Result: call to uppercase_test changes to UPPERCASE_TEST, and widget_base() changes to WIDGET_BASE()
5. Workaround: manually set "routines": "lower" in settings.json (with squiggle-warning & red warning in settings GUI as a result)
6. Would be nice to have routines: lower be a valid option

### Operating System

- [ ] macOS (Intel x86_64)
- [X] macOS (ARM64)
- [X] Linux
- [ ] Windows

### IDL Version

N/A

### Additional Information

PRO UPPERCASE_TEST

END

PRO uppercase_test_func
  uppercase_test
  a = widget_base()
END

**Comment by znorman-harris** [comment]
Thanks for reporting this! I was able to reproduce this. I'll poke around and see why we aren't using the actual settings from VSCode as I would expect.

**Comment by znorman-harris** [comment]
Alright, just fixed this one. Looks like we introduced this bug with a change earlier this year to our formatting code and the bug made its way into our tests, so we didn't catch it and they passed.

Added a specific test that *only* checks this, so we should be able to catch this in the future!
