### ISSUE TITLE
[Bug]: Unknown keyword error reported even though keyword exists

### ISSUE THREAD

**Issue by martinwiesmann** [interactive-data-language/vscode-idl#57]
### Current Behavior

I get the error "unknown-kw", 97 even though the keyword I use is in the function definition:

![Screenshot 2024-11-26 at 14 57 23](https://github.com/user-attachments/assets/c44b4f57-a5fb-4942-89c7-6b714948aa4e)

The function looks like this (from the path /Applications/NV5/idl91/idl):

![Screenshot 2024-11-26 at 14 57 38](https://github.com/user-attachments/assets/b1650d4a-51d1-404e-abfe-c6758c301bd1)

where you can see a keyword 'event_func'. 

The program also works as expected, the function 'spice_xmap_gamma' is called, whenever there is an event in 'gamma_slider'.

The documentation of this function (https://www.nv5geospatialsoftware.com/docs/CW_FSLIDER.html) doesn't mention the keyword 'event_func', but it is clearly in the code, and has been for a long time, since we use it like this for many years.

### Expected Behavior

I would expect that this wouldn't be reported as an error. The IDL extension should know this keyword.

### Steps to Reproduce

1. Use CW_FSLIDER with the keyword 'event_func'
2. see example above

### Operating System

- [X] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [ ] Windows

### IDL Version

9.1

### Additional Information

Obviously, I can just ignore or disable this error message, but that's not the optimal solution.
However, this bug doesn't have a high priority.

**Comment by znorman-harris** [comment]
Thanks for reporting this! I just updated the internal docs for the extension to include this keyword and it will be there in the next release. If you find others like this, you can just report a simple issue with the item missing from the docs (no need for the full report).
 
Looking at our online docs, it doesn't look like this keyword is documented, which we use for the integrated hover help and why it is being reported as "unknown". https://www.nv5geospatialsoftware.com/docs/CW_FSLIDER.html

But, here's a screenshot of it working as expected:

![image](https://github.com/user-attachments/assets/3ffe05ff-b8f7-47ed-86c6-3e158caf42e3)

**Comment by chris-torrence** [comment]
And I just updated the actual IDL help to have this keyword, so it will be there for IDL 9.2.

**Comment by martinwiesmann** [comment]
Great. Thanks for the quick fix.

I assumed that the extension gets the keywords and arguments from the code itself and not from the documentation. But obviously not :)
