### ISSUE TITLE
[Bug]: unknown keyword: align_left in function widget_droplist()

### ISSUE THREAD

**Issue by martinwiesmann** [interactive-data-language/vscode-idl#58]
### Current Behavior

The keyword /align_left is reported as unknown keyword for the function widget_droplist(). It isn't in the documentation, but it works anyway.

### Expected Behavior

Don't report as unknown.

### Steps to Reproduce

1.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [ ] Windows

### IDL Version

9.2

### Additional Information

Did you want me to report these kind of issues like this? Or another way?

**Comment by znorman-harris** [comment]
Thanks! Added this in.

> Did you want me to report these kind of issues like this? Or another way?

Bug reports are OK. You can just have the title be something like "Missing keyword in routine" and don't worry too much about the content of the bug report.

Just the missing keyword and routine are all I need to add these in. If it gets to be a bother, I'll make a discussion where we can put those in, but I'm OK with issues for now!

**Comment by chris-torrence** [comment]
Also fixed in the main IDL docs
