### ISSUE TITLE
[Bug]: Linting tool is applied to task definition files.

### ISSUE THREAD

**Issue by gsf-elefebvre** [interactive-data-language/vscode-idl#7]
### Current Behavior

Whenever I open a .task file the pro code linting tool is applied, resulting in a bunch of syntax errors

![idl-vscode-lint](https://github.com/interactive-data-language/vscode-idl/assets/26776539/00ffe7af-907c-467d-bc42-3e315977f2af)

### Expected Behavior

The task file should behave like a json file and not an idl file.

### Steps to Reproduce

1. Install the IDL for VSCode plugin v3.1.4
2. open an ENVI task (.task) file
3. start making edits in the file and the linting tool highlights the pro code errors.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [X] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment]
Thanks for reporting! Looks like I broke this with some of the changes to support notebooks in the language server.

I'll see if I can get in some tests and push out a new release tomorrow.
