### ISSUE TITLE
[Bug]: Misidentifies STRICTARRSUBS compile option

### ISSUE THREAD

**Issue by HGS-davidstreutker** [interactive-data-language/vscode-idl#8]
### Current Behavior

Linter identifies STRICTARRSUBS as an illegal compile option for COMPILE_OPT.

![image](https://github.com/interactive-data-language/vscode-idl/assets/60927559/74cbbc03-86d6-464d-b7be-640059fc2617)

### Expected Behavior

Linter identifies STRICTARRSUBS as an allowed compile option for COMPILE_OPT.

### Steps to Reproduce

1. Example code:

`compile_opt idl2, logical_predicate, strictarrsubs

print, 'hello world'

end
`

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

IDL 8.9.0 (Win32 x86_64 m64)

**Comment by znorman-harris** [comment]
Thanks for reporting! Sorry I missed that one.

Added it in as a supported compile opt and made a regression test. 

Should have a new version of the extension posted in the next day or so!

**Comment by znorman-harris** [comment]
Just a heads up that I just published a new release (v3.2.3) which has this included.

It should be available in the marketplace in the next 5-10 minutes. You will need VSCode 1.82 to use it though (August version).
