### ISSUE TITLE
[Feature]: Add setting to turn off automatic display of ENVI datasets

### ISSUE THREAD

**Issue by gsf-elefebvre** [interactive-data-language/vscode-idl#9]
### Description

Every time I select a file with a .dat extension in VSCode is launches IDL and ENVI and attempts to open it as an ENVI dataset.  The .dat extension is very generic and you can't assume it's always an ENVI dataset.

### Why it Matters

Every time I select a license.dat file for a git diff it launches ENVI.

### Suggested Behavior

Add a VSCode setting so I can turn it off, if one doesn't already exist.

**Comment by znorman-harris** [comment]
Sorry I didn't respond to this, the GitHub notification emails are getting filtered out as spam for work. Feel free to ping me on teams next time I don't get back to you quickly.

Unfortunately this is either an all-or-nothing kind of feature. Configuring custom editors comes directly from the JSON file that is shipped at the root of the extension itself and lives a bit outside of preferences that are included with the extension.

However, VSCode has a setting for everything! 

Here's how you can disable it:

1. Open the settings UI
2. Search for 'Editor Associations"
3. Enter the extension you don't want to open in ENVI ("*.dat" for example)
4. Set the editor as "default"
5. Hit OK
6. Open a .dat file and it should display in the editor without opening ENVI

Added to the docs and included steps in case others want to disable as well!

https://github.com/interactive-data-language/vscode-idl/blob/develop/extension/docs/general/DISABLE_ENVI_FILE_ASSOCIATIONS.md
